### ISSUE TITLE
Maps do not load in firefox

### ISSUE THREAD

**Issue by RabidOwlbear** [thurianknight/hyp3e#124]
As the title states, on loading of the game world, any created map stalls at 96-98% loading. No errors in console. 
No mods installed. 
Foundry version: 12 build 331, 
System, version: 1.7.1
Firefox version: 138.0.1

Maps load as expected in Cromium browsers.

From the FVTT discord  in response to a user with a similar issue: "Sounds like the system has at least one SVG that isn’t fully defined, which breaks FF in this particular way."

**Comment by RabidOwlbear** [comment]
I found a solution,  or an AI did anyway, here are the changes made that resulted in it working in firefox:
# SVG Rendering Fixes for Firefox Compatibility

## Overview
This document outlines the changes made to fix SVG rendering issues in Firefox, particularly for status effect icons in Foundry VTT. The changes focus on improving rendering performance, ensuring proper scaling, and preventing rendering artifacts.

## CSS Changes
Added to `css/hyp3e.css`:

```css
/* Status effect icon styles */
.token-effect {
  width: 32px;
  height: 32px;
  object-fit: contain;
  -moz-transform: translateZ(0); /* Firefox-specific fix */
  transform: translateZ(0);
}

/* Ensure SVG icons scale properly */
img[src$=".svg"] {
  width: 100%;
  height: 100%;
  object-fit: contain;
  -moz-transform: translateZ(0);
  transform: translateZ(0);
}

/* Firefox-specific SVG fixes */
@-moz-document url-prefix() {
  .token-effect {
    will-change: transform;
    backface-visibility: hidden;
  }
  
  img[src$=".svg"] {
    will-change: transform;
    backface-visibility: hidden;
  }
}

/* Prevent SVG rendering issues in Firefox */
.token-effect img,
img[src$=".svg"] {
  -moz-transform: translateZ(0);
  transform: translateZ(0);
  -moz-backface-visibility: hidden;
  backface-visibility: hidden;
  -moz-perspective: 1000;
  perspective: 1000;
}
```

## SVG File Changes

### 1. `assets/snail.svg`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
  <path fill="#fff" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z"/>
</svg>
```

### 2. `assets/run.svg`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
  <path fill="#fff" d="M13.5 5.5c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zM9.8 8.9L7 23h2.1l1.8-8 2.1 2v6h2v-7.5l-2.1-2 .6-3C14.8 12 16.8 13 19 13v-2c-1.9 0-3.5-1-4.3-2.4l-1-1.6c-.4-.6-1-1-1.7-1-.3 0-.5.1-.8.1L6 8.3V13h2V9.6l1.8-.7"/>
</svg>
```

## Key Improvements

### 1. Hardware Acceleration
- Added `-moz-transform: translateZ(0)` to force hardware acceleration in Firefox
- Added `transform: translateZ(0)` for cross-browser compatibility

### 2. Rendering Optimizations
- Added `will-change: transform` to optimize rendering performance
- Added `backface-visibility: hidden` to prevent rendering artifacts
- Added `perspective: 1000` to improve 3D rendering

### 3. SVG Structure
- Added proper XML namespace declarations
- Added explicit dimensions (24x24)
- Simplified path data
- Removed redundant attributes
- Added proper viewBox for scaling

### 4. Firefox-specific Fixes
- Used `@-moz-document` rule for Firefox-specific optimizations
- Added Firefox-specific transform properties
- Added Firefox-specific perspective properties
